### ISSUE TITLE
Beta/Dev Custom CSS Box text area change

### ISSUE THREAD

**Issue by Happy2Play** [BenZuser/Emby-Web-Dark-Themes-CSS#18]
Not sure how you want to handle this change since it make current code obsolete.  But here is what I did.

Section 2.3
`#txtCustomCss {color: #4285F4; height: 300px !important; overflow-y: scroll !important;}`

**Comment by Happy2Play** [comment]
Beta just went stable.  How do you want to handle this one?

Edit looks like there is a hold on Windows release.

**Comment by BenZuser** [comment]
I cant do anything right now. I'll take a look tonight or tomorrow.

**Comment by Happy2Play** [comment]
Implemented
