### ISSUE TITLE
fix help button colors 

### ISSUE THREAD

**Issue by Happy2Play** [BenZuser/Emby-Web-Dark-Themes-CSS#20]
Change help buttons, accent to .button-accent-flat  (All Server Versions)

/\* Individual Elements _/
/_ ----- 1.2 Details ----- _/
/_ 1.2.1 Icons _/
/_ Multiple Elements */
.starIcon, .button-accent-flat

reference https://github.com/MediaBrowser/Emby/commit/96087e151b1be40039d7bb641fab98f1665ddea5

**Comment by BenZuser** [comment]
done
