### ISSUE TITLE
Beta changes

### ISSUE THREAD

**Issue by Happy2Play** [BenZuser/Emby-Web-Dark-Themes-CSS#21]
Not sure if you want to merge the first two into somewhere that already has that background.

/\* Edit Image Selectors */
# selectImageProvider, #selectBrowsableImageType, #selectImageType {background: #181818; }

/\* Dashboard Access Help Buttons */
# dashboardPage a:nth-child(2) {background: #181818 !important; }

/\* Dashboard Metadata Section Moved background */
# metadataConfigurationPage form div {background: none !important; }

**Comment by BenZuser** [comment]
I don't have access to my beta server test right now so I'l blind trust you on this.
The Image Selectors is from a pop-up right?

**Comment by Happy2Play** [comment]
Here is an example, since the theme is already changing the text to white.

https://emby.media/community/index.php?/topic/39857-image-search-drop-down-boxes/

Currently only in beta/dev.
