### ISSUE TITLE
Image update 3.2.3

### ISSUE THREAD

**Issue by Happy2Play** [BenZuser/Emby-Web-Dark-Themes-CSS#24]
/* 2.2.4 Others */
/* Image Files */
.imgLogoIcon, .adminDrawerLogo img {
  content: url(https://cdn.rawgit.com/BenZuser/Emby-Dark-Themes-Resources/master/images/logos-and-icons/BLUE/logo.png) !important; }

to

**h3.libraryMenuButtonText.headerButton** img {
  content: url(https://cdn.rawgit.com/BenZuser/Emby-Dark-Themes-Resources/master/images/logos-and-icons/BLUE/logo.png) !important; }

**Comment by Happy2Play** [comment]
/* 2.2.4 Others */
/* Image Files */
.imgLogoIcon, .adminDrawerLogo img {
  content: url(https://cdn.rawgit.com/BenZuser/Emby-Dark-Themes-Resources/master/images/logos-and-icons/BLUE/logo.png) !important; }

to

h3.libraryMenuButtonText.headerButton img {
  content: url(https://cdn.rawgit.com/BenZuser/Emby-Dark-Themes-Resources/master/images/logos-and-icons/BLUE/logo.png) !important; }

**Comment by BenZuser** [comment]
Cool! thanks.
