### ISSUE TITLE
Useable for newest Emby version?

### ISSUE THREAD

**Issue by Siutsch** [BenZuser/Emby-Web-Dark-Themes-CSS#26]
Hi.
I use Emby for 2 weeks now (Premiere), and I found your dark themes.
But it happens nothing, wenn I paste under Custom CSS.
Do I something wrong?

Thanks.

**Comment by BenZuser** [comment]
The dark theme only works with the web app by using your personal IP address (or localhost if you're local).
It doesn't work if you use http://app.emby.media/ unfortunately.

**Comment by Siutsch** [comment]
I use it lokal (https://192.168.0.253:18097).
But it runs on my HTPC, I use the web app from my laptop.
Have I use that on the same machine?

**Comment by BenZuser** [comment]
Do you copy the whole code or the one mentionned here https://benzuser.github.io/Emby-Web-Dark-Themes-CSS/

Something like this :

@import url('https://rawgit.com/BenZuser/Emby-Web-Dark-Themes-CSS/master/RED/theme.css');

**Comment by Siutsch** [comment]
Tried both from this side: https://benzuser.github.io/Emby-Web-Dark-Themes-CSS/
Complete code, that is in the clipboard and only the URL.

**Comment by BenZuser** [comment]
I'm not sure why it doesn't work though... Do you use a popular web browser like Google chrome, firefox, etc?

**Comment by Siutsch** [comment]
I use Firefox (latest version 53.0.1).
Emby is 3.2.7.0 and runs on my HTPC (Windows10 x64).
Have I paste the string, which is in the clipboard, that begins with @import url?
Or onyl the https URL?

I try it with Chrome and Edge now too ...

**Comment by Siutsch** [comment]
Works with Chrome! :)

**Comment by BenZuser** [comment]
Yes you have to keep the whole line with @import url(...);

Yeah, I'm sorry, I only test my themes  with chrome (Edge sometimes).

**Comment by Siutsch** [comment]
No problem. Something must be different with FF.

**Comment by Happy2Play** [comment]
Yes there are topics on the forum about Firefox not accepting/saving custom css.  You just have to try a different browser.  Most development is done it Chrome but tries to be compatible with most modern browsers.
