### ISSUE TITLE
Login and Home screen logo rework

### ISSUE THREAD

**Issue by Happy2Play** [BenZuser/Emby-Web-Dark-Themes-CSS#27]
Reworked code as content doesn't work on IE, Edge, or Firefox.
/*Login screen logo*/
img.imgLogoIcon {
    width: 0;
    height: 0;
    padding: 40px 0 0 131px;
    background: url(https://cdn.rawgit.com/BenZuser/Emby-Dark-Themes-Resources/master/images/logos-and-icons/BLUE/logo.png);
    background-size: 100% 100%;
}
/*Home Screen logo*/
h3 img {
    width: 0;
    height: 0;
    padding: 0 0 0 66px;
    background: url(https://cdn.rawgit.com/BenZuser/Emby-Dark-Themes-Resources/master/images/logos-and-icons/BLUE/logo.png);
    background-size: 100% 100%;
}

**Comment by BenZuser** [comment]
Thanks! The login screen logo doesn't seem to load for Edge though.

**Comment by Happy2Play** [comment]
It loads for me in Edge.  Only thing I notice on login screen is if the screen is to small the logo disappear.  But that happens in all browsers that I have tested on.

**Comment by BenZuser** [comment]
ok that's strange. It loads on Chrome but not in Edge on the same screen for me.
