### ISSUE TITLE
Code blocking video player

### ISSUE THREAD

**Issue by Happy2Play** [BenZuser/Emby-Web-Dark-Themes-CSS#37]
Not sure how you want to handle this but this section of code is blocking video player in all browsers.

/* 3.2.4 Backgrounds */
/* Main Backgrounds */
.background-theme-a .backgroundContainer,
.background-theme-b .backgroundContainer {
  background-color: #141414 !important; }

that code overwrites this background-color to show video player.

.transparentDocument, .backgroundContainer-transparent:not(.withBackdrop) {
    background: none !important;
    background-color: transparent !important;
}

Removing ".background-theme-b .backgroundContainer"  seems to resolve the issue but I don't know if there are other side effects.

**Comment by BenZuser** [comment]
How inconvenient! Since I want to be sure both dashboard and home page have the same background color, removing !important did the trick.
