### ISSUE TITLE
The latest Emby server Beta release has broken the CSS

### ISSUE THREAD

**Issue by CBers** [BenZuser/Emby-Web-Dark-Themes-CSS#47]
I think the latest [url="https://github.com/MediaBrowser/Emby/releases/tag/3.2.26.4"]Emby server Beta release[/url] (v3.2.26.4) has broken the CSS. 

I've had to remove it to be able to see content. 

It's like white text on a white background.

See here: https://emby.media/community/index.php?/topic/28743-emby-dark-themes-in-different-accent-colors/page-17#entry470597

Thanks.

**Comment by BenZuser** [comment]
Thank you!
