### ISSUE TITLE
Beta 3.1.86

### ISSUE THREAD

**Issue by Happy2Play** [BenZuser/Emby-Web-Dark-Themes-CSS#9]
Wasn't sure how you wanted to handle this so I just opened an issue instead of a pull request.

Since rework of card layout not sure what is no longer need.

Restart-Shutdown pop-up options not sure what the rest of the **.dialog .button** options you have listed go to.

.btnOption.dialogButton {color: #ffffff !important; } went with White lettering, looked better then theme color.

.btnOption.dialogButton:focus {background-color: #0C57D6 !important; }

Needs Removed or reworked not sure the route to take: unable to see watched or favorite when selected.  I removed in custom css for testing.  Not sure if you have any other ideas for it.
[is="emby-button"].raised, [is="emby-button"].fab {
  color: #FFFFFF !important;
  background: #404040;
  border-color: #404040; }

**Comment by BenZuser** [comment]
I know there's a lot of unused codes now. I have to clean up (maybe this weekend if I have time?).

For the dialog buttons, if I do it the same way it is for the other pop-ups, it would be like this : 

.dialogButton {
    color: #4285F4 !important;
    background-color: transparent !important;}
.dialogButton:hover {
    color: #9b9b9b !important;
    background-color: transparent !important;}

We have this other solution, but the other pop-ups would have to changed also : 

.dialogButton {
    color: #4285F4 !important;
    background-color: transparent !important;}
.dialogButton:hover {
    color: #ffffff !important;
    background-color: #4285F4 !important;}

For my personnal preference, I prefer the 1st one but I don't know, which one you would keep?

**Comment by Happy2Play** [comment]
I would stick with the first one.

**Comment by Happy2Play** [comment]
As for the second issue here is an example.

with code all you get is white when selected or not
![played-favorite2](https://cloud.githubusercontent.com/assets/10268557/17347661/2c121082-58c6-11e6-976c-79cfa1ad3cb7.jpg)

and without code you see selection
![played-favorite](https://cloud.githubusercontent.com/assets/10268557/17347670/3c414270-58c6-11e6-8b37-4872d53e8a15.jpg)

**Comment by Happy2Play** [comment]
I see the issue removing [is="emby-button"].raised causes issues with some of the Cancel buttons.
So just dropping [is="emby-button"].fab  is the solution, since they are .fab buttons.

[is="emby-button"].raised {
 color: #FFFFFF !important;
 background: #404040;
 border-color: #404040; }

**Comment by BenZuser** [comment]
I don't know how to fix this second problem. I'll try to figure out later.

**Comment by BenZuser** [comment]
All I know is that the issue is somewhere in section 4.1

**Comment by BenZuser** [comment]
Ok, thanks.
